#!/bin/sh
# shellcheck shell=sh
#
# backend_odhcpd.sh - launch a real odhcpd server as the DHCPv6 + RA backend.
#
# This is the "real-server backend": the natural OpenWrt counterpart to
# odhcp6c. It is best for realistic bound/renew/rebind flows on the happy path.
# It requires the `odhcpd` binary to be present in the image (the harness
# Dockerfile builds it from source); if it is missing the scenario should fall
# back to the scapy backend.
#
# odhcpd is configured here through a minimal generated UCI-free config: we drive
# it with a small interface configuration written to a temp file. Because odhcpd
# is normally configured via OpenWrt UCI/ubus, the harness invokes it with a
# generated config directory and the environment overrides it understands. The
# exact knobs differ between odhcpd versions, so this backend keeps the config
# deliberately small and documents the assumptions.
#
# The server runs in the server netns and serves the server-side veth with a
# global ULA prefix so it can hand out IA_NA/IA_PD and advertise RAs.

: "${ODHCPD_BIN:=odhcpd}"
: "${ODHCPD_PREFIX:=2001:db8:1::/64}"
: "${ODHCPD_PD_PREFIX:=2001:db8:abcd::/48}"

backend_start() {
	command -v "$ODHCPD_BIN" >/dev/null 2>&1 || \
		fatal "odhcpd backend requested but '$ODHCPD_BIN' not found in image"

	# Give the server side a routable global address so it can serve leases and
	# originate RAs for the configured prefix.
	$SUDO ip netns exec "$HARNESS_NS_SERVER" \
		ip -6 addr add "${ODHCPD_PREFIX%/*}1/64" dev "$HARNESS_VETH_SERVER" \
		2>/dev/null || true
	$SUDO ip netns exec "$HARNESS_NS_SERVER" \
		sysctl -qw net.ipv6.conf.all.forwarding=1 2>/dev/null || true

	_cfgdir="$HARNESS_WORKDIR/odhcpd-cfg"
	mkdir -p "$_cfgdir"
	# Minimal odhcpd config; odhcpd reads OpenWrt UCI in production. For the
	# harness we rely on the environment + command line. Newer odhcpd accepts a
	# config path via -c; older builds require ubus. The scenario selects this
	# backend only when the image provides a compatible odhcpd.
	cat > "$_cfgdir/odhcpd.conf" <<EOF
# Generated by the odhcp6c harness (backend_odhcpd.sh).
# interface: $HARNESS_VETH_SERVER
# ra: server, dhcpv6: server
# na-prefix: $ODHCPD_PREFIX
# pd-prefix: $ODHCPD_PD_PREFIX
EOF

	$SUDO ip netns exec "$HARNESS_NS_SERVER" \
		"$ODHCPD_BIN" "$HARNESS_VETH_SERVER" \
		> "$HARNESS_WORKDIR/backend.log" 2>&1 &
	HARNESS_BACKEND_PID=$!
	log "odhcpd backend started (pid $HARNESS_BACKEND_PID) on $HARNESS_VETH_SERVER"

	# odhcpd has no machine-readable "ready" marker; give it a brief, bounded
	# warm-up to open its sockets.
	sleep 1
}

backend_stop() {
	[ -n "$HARNESS_BACKEND_PID" ] || return 0
	$SUDO kill "$HARNESS_BACKEND_PID" 2>/dev/null || true
	wait "$HARNESS_BACKEND_PID" 2>/dev/null || true
	HARNESS_BACKEND_PID=""
}
